sudo: required

services:
  - docker

branches:
  only:
    - master
    - /^v?\d+\.\d+(\.\d+)?(-\S*)?$/
    - refact/improve-cache-on-ci

script: 
  - bash scripts/docker-build.sh
  - bash scripts/docker-push.sh
